Fix doctests
After the last commit, doctest is now failing to run:

```
test/Test/LinearLocks/MutexSetSpec.hs:14:1: error: [GHC-45102]
    Ambiguous module name ‘Test.Tasty.HUnit’.
    it was found in multiple packages:
    tasty-hunit-0.10.2 tasty-hunit-compat-0.2.0.1

test/Test/LinearLocks/MutexSpec.hs:19:1: error: [GHC-45102]
    Ambiguous module name ‘Test.Tasty.HUnit’.
    it was found in multiple packages:
    tasty-hunit-0.10.2 tasty-hunit-compat-0.2.0.1
```

Turns out, just having`tasty-hunit-compat` declared in stack's `extra-deps` causes doctest to have both `tasty-hunit` and `tasty-hunit-compat` in scope, leading to this ambiguous module name error.

We don't even have to have `tasty-hunit-compat` listed as a package dependency. Just being in extra-deps is enough.

---

One possible solution would be to add `drop-packages: - tasty-hunit` in stack.yaml.
But `tasty-hunit-compat` depends on `tasty-hunit`, so we can't actually drop it.

Another solution could be to migrate from `doctest` to e.g. `doctest-parallel`, which has better stack/cabal integration. But it only picks up doctests from the library component, and I need it to pick up doctests from the test suite as well (and the `examples` folder).

Lastly: we can use `PackageImports` to specify which package we want to import `Test.Tasty.HUnit` from.